### PR TITLE
Add inspector window

### PR DESCRIPTION
**Pull request by wandernauta**
This PR adds an 'inspector' window that shows the expression tree as well as
the generated Haskell source for the selected block.

Since #82, CustomUIPane is no longer notified when the program changes, so you
may have to click the 'refresh' button on the Inspector if you change your
program and it doesn't seem to update.

The window is shown when the Z key is pressed.

### CODE REVIEW

**Comment by wandernauta** [comment]
2015-05-18-205142_1409x975_scrot

**Comment by wandernauta** [comment]
Investigating failing unit tests.

**Comment by wandernauta** [comment]
Unit tests are green.

**Comment by jjkester** [comment]
Nice feature! Helps debugging the code and with demonstration purposes.

**Comment by wandernauta** [comment]
Thanks for the review!

**Pull request merged**
