### PR TITLE
Make GhciSession NOT a Singleton

### PR DESCRIPTION
**Pull request by wandernauta**
There were reasons for making GhciSession a singleton, but none of them
were very good. This commit reverts that and has CustomUIPane carry
along an optional GhciSession.

### CODE REVIEW

**Comment by TheMSB** [comment]
I am still interested in the reasons in favour of a singleton approach in the event you mind sharing them.

**Comment by wandernauta** [comment]
Sure.

Back in the day, during FP class, ghci occasionally took a sweet time (a few seconds) starting up, as it had to load quite a lot of libraries as well as compile some user code.

I wanted to be absolutely sure that the painful multiple-second initialization was only ever done once, not once per test for example. Hence a singleton. However, it turns out that starting ghci with only `Prelude` and `Data.List` imported is pretty fast, and there aren't many tests, so there's really no need.

**Comment by jjkester** [comment]
(Y)

You have my permission to merge this yourself and resolve any conflicts. (If you want me to do it, just let me know.)

**Comment by wandernauta** [comment]
Merged, thanks for taking a look!

**Pull request merged**
