### PR TITLE
UI refactoring

### PR DESCRIPTION
**Pull request by TheMSB**
Refactored several classes:

 * Each UI Component type now resides in their respective package, Blocks in blocks, Anchors in anchors etc.

 * I noticed that all of the UI Component classes had duplicate code in their constructors, attempted to refactor by creating abstract class Component, sadly I ran into complications with ConnectionLine and Circle because of multiple inheritance, I tried composition but it seems hard to implement with FXML access.

 * Blocks respective toString method has now been refactored into a one serves all toString in Block.

 * Attempted to create a more generic setAnchor method for Connection but am having difficulties because of the Optional Generics.

### CODE REVIEW

**Comment by wandernauta** [comment]
Looks good overall. A few things:

- Even with your refactored Component class, constructors still throw IOExceptions. Do you have an idea how we can get rid of those? 
- The new `setAnchor` looks needlessly complex. You shouldn't have to cast Optionals at all. Check out the Java 8 docs if you haven't already - if you have, it might help to think of Optional as an ArrayList that always has one or zero elements.

**Comment by TheMSB** [comment]
This last commit should fix the last few things. Final notes:
 * setAnchor works but has potential for further refactoring.
 * catch clause in base components needs useful catch (or we need to refactor FXMLLoading even further.

I will introduce no further changes but will rebase the commits so only code that was strictly needed ends up in master.

**Comment by wandernauta** [comment]
The ComponentLoader 'interface' doesn't seem to fix the IOException problem. It's also not really a loader: the actual loading only happens when `.load()` is called on the result.

Maybe I'm just not 'getting it', but could you explain what the ComponentLoader does and why it's useful?

**Comment by TheMSB** [comment]
The idea behind ComponentLoader is that it provides a default implementation for the loading of the FXML. Now each Component only has to use one method to instantiate it's FXML instead of having the same 4 lines in each constructor. 

On a side note the reason .load() is called on the result instead of being called right away is to prevent FXML complaining about the root of the FXMLLoader. If you want to see what happens try calling .load() right away.

**Comment by wandernauta** [comment]
Okay.

**Pull request merged**
