### PR TITLE
Fixed whitespace and javadoc for PR #51

### PR DESCRIPTION
**Pull request by TheMSB**

### CODE REVIEW

**Comment by wandernauta** [comment]
No, this is not what I meant, see my last comment on PR #51.

**Comment by TheMSB** [comment]
> No, this is not what I meant, see my last comment on PR #51.

You mean the bit about custom UI Pane?

**Comment by wandernauta** [comment]
This PR at first glance seems to be the whitespace changes from #51. I don't want the whitespace changes from #51 and disagree with most of them. What I would like to be able to do is look at (and perhaps eventually merge) the functional changes from #51.

**Comment by TheMSB** [comment]
I see your point, I will leave it to @i3anaan  to fix them then, I don't know what he changed exactly and why.

**Comment by wandernauta** [comment]
Thanks. Now, if you come across some part of master that you think is ugly or hard to read, feel free to submit a PR, as always.

**Pull request closed without merging**
